### ISSUE TITLE
BOOL ARRAY data type allows limited element count

### ISSUE THREAD

**Issue by GitHubDragonFly** [libplctag/libplctag#187]
The element count is limited to the number of DINTs that hold the bool array.

A bool array is named "alarms" and declared as BOOL[320] (which is 10 x DINT).
Polling alarms[0] with any element count higher than 10 returns error.

Using @tags to get tags list also reports this bool array as alarms[10] of DINT type and 4 bytes size.
If it is this dimension that is used in code then it should be multiplied by 32 bits.

**Comment by kyle-github** [comment]
See issue #82.   This is a known "feature" of the underlying protocol and type handling in the PLC.

There are other challenges here.   For instance in UDTs, single booleans are all packed into a single 8-bit word at the beginning of the UDT (not in field order) if there are 8 or fewer.  If there are more, then they are packed into 32-bit or 64-bit words (I can't remember right now), at the beginning of the UDT.  I seem to remember that large BOOL arrays are handled as "normal" fields within a UDT, but it has been a while since I dug into that.

The existing C API calls `plc_tag_get_bit()` and `plc_tag_set_bit()` allow you to access any integral type as an array of BOOL.  But that does not solve the problem.

Unfortunately the CIP protocol does not appear to allow us to request all of a tag.   It requires a count and treats all tags as arrays (even if they only have one element).   There are a few cases where sometimes the error returned will tell you the correct size (for instance when using newer firmware versions you can often get the correct packet size to negotiate to when setting up a CIP connection), but this is not one of them.   When you request more of a tag than exists, you get a simple error back without any additional data.

The Modbus support does allow specifying boolean arrays, but only as a side effect that there are only two types of underlying register.   AB does not have that simplicity.

So far, the possible ideas all require that the something provide some type information to the library.   I.e. an extra attribute that says that the base size calculation is in bits instead of bytes.   An alternative is to read a element count of 1 initially, check the returned type (a BOOL array does not return the same type as DINT) and then process the full element count based on that.  Using the @tags tag listing only works for top-level tags.

I would like it to be possible to simply provide the name of the tag and have the library figure the rest out from there.   Unfortunately, there are either undocumented protocol calls that AB uses to do this or they do it the hard way as well.   What we really need is the ability to query, for a single tag, the type information you get back from the tag listing.   I am sure that AB has a way to do that, but I have not seen anything documented.   

The only way I am aware of is to list all the tags, search for the one you want and then use that type information.  If the tag is a UDT, then you have to do another set of searches to find out the information for that UDT type which could be deeply recursive if the UDT contains other UDTs.   Within those calls you can enumerate the fields and would have to search for the one you want.   It would be possible to do this, but it is significant complexity to add to the library and would be a feature that would need to be removed when the library is used in an embedded application due to the amount of memory and processing that would be required.   This is much more suited to handling in the wrapper layer.

And this would not be supported on any CIP PLC that does not allow tag listing such as Micro800 and possibly Omron.  Additionally it would be PLC-specific, for instance Omron returns the entire tag and requires the `elem_count` to always be 1.

Are you actually seeing your BOOL array reported as DINT?   When I do this I get:

`Tag "TestBOOLArray[4]" (20d3): protocol=ab-eip&gateway=10.206.1.39&path=1,5&plc=ControlLogix&elem_size=4&elem_count=4&name=TestBOOLArray`

The base type is 0xD3 which is a 32-bit bit string.  DINT is type 0xC4.  There are other bit string types for 8-bit, 16-bit, and 64-bit, so those cases exist as well.  Single bit BOOL tags are 0xC1 with the bit offset as another part of the type word.

**Comment by GitHubDragonFly** [comment]
Current pattern for BOOL ARRAY data type in your library is like this:

- alarms[32] limits the element count to 1 consecutive bool values anywhere in the array
- alarms[320] limits the element count to 10 consecutive bool values anywhere in the array
- alarms[352] limits the element count to 11 consecutive bool values anywhere in the array

With @tags, they are reported as alarms[1], alarms[10], alarms[11] respectively, with their own data type and with a size of 4 bytes each. All is indicative of DINT data type even though it's reported as its own type.

A good side of your library is that currently it allows using different data types for the same tag.

For example, using DINT type instead to poll the alarms[320] array for 10 elements  (so: name=alarms, elem_size=4, elem_count=10) will get all 10 DINTs holding the array and then one can create a routine that is processing all the bits out of these values by using plc_tag_get_bit() and plc_tag_set_bit().

Another example would be for MicroLogix, where I can poll N7:0 with either of (U)Int8 / (U)Int16 / (U)Int32 / (U)Int64 data type, which virtually allows 64-bit numbers be used with MicroLogix (just like Modbus holding registers).

The official manual doesn't encourage the use of BOOL ARRAY unless it's to be used with PanelView.

So, this is not really an issue unless you can make some changes in the library that could improve support for boolean values.

**Comment by kyle-github** [comment]
One other problem with BOOL arrays is how to write them safely.  I have an addition to the library that supports single bit tags.   So you can access `myDint.14` for instance.   There is a protocol command that will mask and set just the single bit.  Thus, it is safe to write that tag at any time.  Otherwise you overwrite the entire set of bits.

Unfortunately, the command only works with masks up to 12 bytes.  So the maximum I can do is 3 32-bit words.

**Comment by GitHubDragonFly** [comment]
As it appears, your BOOL ARRAY data type, as it is currently, allows manipulating a single DINT of the array (where the bit is).

I can read and write just by calculating the position of the DINT without affecting the rest of the array.

The example could be bool array alarms[352] which in DINTs is alarms[11] with the DINT position ranging from 0 to 10.

Trying to read/write the alarms[75] bool value gives me the DINT position of 2, so the tag ends up with "&elem_size=4&elem_count=1&name=alarms[2]".
The index of 75 then has to be reduced by the total number of bits in preceding DINTs, which is 32 in DINT[0] + 32 in DINT[1], ending up to be 75 - 64 = 11 (eleventh bit of the 3rd DINT).

**Comment by GitHubDragonFly** [comment]
Modbus has function code 22, which is called Mask Write Register, and if you look it up on the Internet then you might be able to figure out a way of implementing it in your library.

Here is one of the links you can check:

https://www.mathworks.com/help/instrument/modify-the-contents-of-a-holding-register-using-a-mask-write.html

From my understanding of Modbus, the slave device on the other end has to support function code 22 in order for it to work.

**Comment by kyle-github** [comment]
BTW, in your example of alarms[352], you can use the C function `plc_tag_set_bit(tag_id, 351)` to set bit 351 (last bit).   So in your code that uses the array, you do not need to write all the code to figure out which 32-bit word the bit is in.

Modbus is going to be a learning experience.   It is very simple compared to EIP/CIP, but at the same time there are many differences between models (and even firmware versions) of PLCs.

**Comment by GitHubDragonFly** [comment]
My example works for a single bit as well as consecutive bits regardless of whether they are overlapping the DINTs.
It allows for manipulating all the bits before the DINT or DINTs are written back to the PLC.

For now, I will stick with my way since it seems to be working properly.

As for the Modbus reading of Coils or Discrete Inputs with BOOL data type, things look like this (don't hesitate to provide different suggestions so I could correct it):

- Requesting up to 8 consecutive bool values can be done with elem_size=1 where 1 byte is returned
- Requesting more than 8 consecutive bool values has to be done with elem_size=2 where the number of bytes returned depends on the number of values requested, is even number of bytes and all these bytes are in reverse order (being 76543210)

**Comment by kyle-github** [comment]
Thanks for pointing out the Modbus command.   I will add that to the list!

I think I was not clear with my example.  The `plc_tag_get/set_bit()` functions will automatically figure out which byte to access in the tag's backing buffer and will let you read or write any individual bits.  So you just read in the whole array as DINTs in a single tag, read and write whichever bits you want, and write the whole thing back out.   Tags are relatively cheap though, so you can do what you are talking about with about as much ease.

Note that when you write such a tag back to the PLC, it is not safe if the PLC can update the bits independently.  The Read-Modify-Write command must be used to be safe.   EIP/CIP has this but it is strangely limited to masks that are up to 12 bytes long.   Right now I only use this command internally if you have a bit tag.  I plan to eventually extend this, but I do not want to expose the 12 byte limit, so I will need to make it smart and automatically send multiple updates for long arrays.   Alternatively, I could just enable up to 12 bytes of array for now and extend it later.   That is 96 bits.   Seems kind of annoying to be limited.   I think I have some PLC code somewhere with 4 DINTs uses as a bit array.

For Modbus, it is actually easier.   I know the register type (register or coil) from the name.   That gives me the size of one element.   The `elem_count` gives me the total elements and then I just round up to the nearest byte and use that as the tag size.   So all you need is the register name and the element count. 

What would a good API for bit arrays/BOOL arrays look like for your use cases?  I have thought about adding masked read and write functions or adding masks to the tag definition string.  I welcome any ideas you have!

**Comment by GitHubDragonFly** [comment]
Reading a whole BOOL Array is what I used to do with older versions of your library, when it wasn't as functional as it is today.
Since you are suggesting that it is a better way of doing things then everybody should do it that way.

Some users might be accustomed to Modbus addressing such as 00000, 100000, 300000, 400000 instead of co0, di0, ir0, hr0.
Either way, the end result is still the same.

Also, SwapBytes and SwapWords terminology for the byte/word order in 32/64 bit values, which you appear to have implemented in tag_rw, and such a request could be passed as optional &swapbytes=true&swapwords=true in the libplctag string for as long as you can manage to implement that in your library (just store all the received values in the order user requested). This would eliminate the need for users to write those routines in their software.

Even limited mask read and write, if implemented in the library and announced as such, could benefit some users.

**Comment by GitHubDragonFly** [comment]
Just a bit more on the SwapBytes and SwapWords possible optional Modbus features:

SwapBytes = true as the default value for 16-bit
SwapBytes = true & SwapWords = true  as the default values for 32-bit
SwapBytes = true & SwapWords = true & an additional ByteOrder64 = 4321  as the default values for 64-bit
