### ISSUE TITLE
Passing some user data to the event callback

### ISSUE THREAD

**Issue by nikitapogodin** [libplctag/libplctag#212]
When using the library from C++ code, it would be very useful to be able to pass user data when registering callbacks and return them back in callback calls.
This for example can be used to bind a callback to a C++ class instance (passing _this_ pointer as user data)

API could looks like:
void plc_tag_register_callback(int32_t tag_id, void (*tag_callback_func)(int32_t tag_id, int event, int status, void* used_data), void* user_data);

**Comment by kyle-github** [comment]
Hi, thanks for proposing this.   I started with this exact API.  It is "traditional" for C-like languages.   Unfortunately, it does not work well for languages that move data around such as any language with generational GC.   I.e. Java, C#...   The problem is that the pointer becomes invalid the moment that GC runs and moves the object in memory.   There is no way to tell the C code that the stored pointer must be updated.

In C++, I suggest making a static map between the int32_t of the tag handle ID and the C++ object you want.   Then when the callback is called, you can look up the C++ object.  It is not quite as ergonomic as getting a pointer to a C++ object instance, but it does allow the same API to be used for all the wrapper languages.

This last point is what led me to the current API: it had to work for all possible wrapper languages.

If you know of a way to solve the GC problem, I would love to add an API for callbacks that allowed passing in data!  Really, if you have any idea at all how to solve this, I am very interested!

Please re-open if you have any ideas!
