### ISSUE TITLE
Connection Issue When Processor Is Deep In Rack ex.. Slot16

### ISSUE THREAD

**Issue by oOICEMANOo** [libplctag/libplctag#443]
Having issues with setting the CIP path when the processor is at the end of the rack (slot 16 *not common I know..) setting the path 1,16 don't seem to work? any suggestions on how to format the CIP to work....

![Capture2](https://github.com/libplctag/libplctag/assets/39998427/1950ac2f-ead8-42a3-a6fb-15af6ff576a9)

![Capture](https://github.com/libplctag/libplctag/assets/39998427/f2b0d15b-640e-46a5-bf06-8807e6669144)

**Comment by kyle-github** [comment]
This is an interesting one. Slots up to 15 (0-15) are handled with a single byte in the constructed path byte string. A value of 16 and up (not sure to what actual value) indicates a port. So for instance, when bridging through a network module the leading byte before the IP address would be either 18 or 19 (decimal) indicating that the address is a port, and then the value above 16 is the actual port number. Port 2 (byte value 18) would be the first external Ethernet port on an ENBT for instance.

Hmm, I see that I am checking for out of bounds values...

    /* was the numeric segment valid? */
    if(val < 0 || val > 0x0F) {
        pdebug(DEBUG_WARN, "Numeric segment in path at position %d is out of bounds!", (int)(ssize_t)(*path_index));
        return PLCTAG_ERR_OUT_OF_BOUNDS;
    }

That check may not be correct, but it will require some tricks to make sure that parsing the path string works correctly if that is not done.

I don't have a chassis with that many slots. Let me see what I can code up.

I am calling this a bug since real hardware apparently can have 17 slots!

**Comment by kyle-github** [comment]
I called this an enhancement.   It turns out that to get values over 15, there is a different encoding that has to be done on the link portion of a port segment.  This is related to and will be fixed by the fix for #462.

**Comment by kyle-github** [comment]
It is really annoying that GitHub does not support linked issues.   There's simple and then there's too simple.

**Comment by blaine-dodson** [comment]
Is there a specific commit/release that resolved this issue? I am seeing similar behavior (BAD GATEWAY) when trying to communicate with slot 16 even on version 2.6.16 .

**Comment by kyle-github** [comment]
I still have no hardware, but the attempt at fixing this will be in 2.7.0.

**Comment by kyle-github** [comment]
This might work.  Please test.

**Comment by blaine-dodson** [comment]
> This might work. Please test.

Looks promising. I think I had resolved the problem with a patch similar to this one-liner: [src/libplctag/protocols/ab/cip.c](https://github.com/libplctag/libplctag/compare/v2.6.16...v2.7.0#diff-a9bf79345c278712de90eba4b7433fac2f7117ef6d4b9328471660b69ead2793)

I'll try it in the week and let you know.

**Comment by blaine-dodson** [comment]
Sorry for the delay. I can confirm version 2.7.0 does communicate with slot 16.

**Comment by kyle-github** [comment]
Thanks for testing!
