### ISSUE TITLE
Data checking

### ISSUE THREAD

**Issue by AAT-SMD** [libplctag/libplctag#449]
I'm using libplctag to communicate with a Rockwell / Allen Bradley PLC, without any issues (at least so far).

I've had a query from a colleague about whether the tag data is verified in some way when reading and writing - for example, when writing to a tag is there a risk that the tag on the PLC ever gets set to a different value to the one requested (due to Ethernet package corruption or anything like that)?

I've never seen any issues like this myself, but it would be useful to know if there's anything built into the library or the protocol - some sort of checksum, or verifying tag writes by reading back, or anything like that.

**Comment by kyle-github** [comment]
There is always some possibility of corruption due to all kinds of factors up to and including cosmic rays flipping bits in RAM (really, it is surprisingly possible since very few PCs or PLCs have error-corrected RAM).   But realistically, the possibility is quite small.   All communications with the PLC go over TCP/IP channels.   TCP has checksums and length checks inherent in each packet.  If the checksums do not match, the packet is resent.   If a packet is missing, it is resent.  On top of that EIP (EtherNet/IP, CIP over Ethernet) has length and type checks.   And CIP has some as well.  TCP is quite reliable.  Most of the Internet is based on it.

The library does not do readback.   This doesn't make sense to do generally (sadly a lot of PLC programs modify the tags being written, so you can have race conditions).  You can do it yourself by triggering a read immediately after every write.  Unfortunately, the underlying CIP protocol does not automatically send the new tag value after a write.

I have never seen actual data corruption due to errors in the network or networking equipment that did not just result in completely lost packets and retries.   However, there is _NO_ coordination between a network module and the PLC program.  So if you have a composite data structure (an array, or UDT) and your PLC program modifies it while you are reading it, you can get the first part of the data structure with the new data and the last part with the old data.   I have _definitely_ see this and had systems fail or behave strangely due to this.   

In order to work around that, I put what I call sentinel values at the beginning and end of each UDT or in the first and last elements of an array.   When the PLC program is going to start to modify the tag, it first calculates a new sentinel value.  It puts that as the first word in the data structure.  It then changes all the other data.  At the end it puts the new sentinel value in the last word of the data structure.  On the PC side, the program looks at the sentinel values.  If they match, then you know that you got the data structure cleanly without the PLC changing values while you read it.   If they don't match, you need to read again.  I call this error **tearing**.

I cannot emphasize just how common this is.   I had one system where we were dealing with someone else's code and the original programmers had a UDT that was about 9000 bytes long that represented almost all system state.   We could almost _NEVER_ read it without tearing.   Once we figured out what was happening, we had to break up the UDT and use the sentinel idea on the pieces.

We initially tried to work around tearing by copying the changed tag into a secondary tag using a block copy instruction.   The PC read the secondary tag.   It helped, but did not eliminate the problem.

Note that tearing has nothing to do with libplctag.  If you have a PLC program that reads a tag from another PLC, you will see the same thing.   Even writing the value from one PLC to the other doesn't eliminate the problem.   The tearing then occurs on the other PLC.

Note that you _can_ (not with libplctag) use UDP for transporting CIP commands to the PLC.   In that case, you have a number of problems:

- you can still get tearing.
- you are limited to roughly 500 bytes of data.
- you can get complete packet drops.  So make sure you have a sequence ID somewhere.

Note that produced/consumed tags use UDP, not TCP, generally.  So you can get missing packets and tearing.  IO goes through UDP as well.

Please reopen the question if you need more information
