### ISSUE TITLE
String Write is not working for Omron NJ/NX Controller

### ISSUE THREAD

**Issue by salma4791** [libplctag/libplctag#451]
Write operation for string datatype is not working. it is giving PLCTAG_ERR_TOO_LARGE while setting the string using plc_tag_set_string API. Observed that the string capacity is less than the string length due to which it is throwing this error.

**Comment by ptsOSL** [comment]
Have you seen [https://github.com/libplctag/libplctag/issues/431]? There might be some information there to help you. I have managed to get writing to strings on the Omron NJ working, however in addition to correctly setting the additional tag attributes, I had to do two other things. First, I had to manually set the size of the libplctag tag buffer using `plc_tag_set_size()`, this is because I was trying to write a longer string to the PLC STRING variable than was currently stored in the PLC. This meant that the libplctag tag buffer was too small to store the data I wanted to write to the PLC, I think this might be your problem. Another issue I had was that libplctag forces padding to an even number of bytes, you may encounter this problem if you fix the first issue. There is more detail about this on the linked issue. 

Would it be appropriate for me to create another tag string attribute which allows the user to enable/disable having this string padding and create a pull request @kyle-github?

**Comment by salma4791** [comment]
Yes i have seen the string issue hub but the plc_tag_set_size() is still not helping me because for Omron NJ/NX , the string datatype is appended with null byte. Additionally i have figured out that the length of the string while writing is not calculated properly.

**Comment by ptsOSL** [comment]
I have created a pull request to fix the issue with the appended null byte, I understand that this is necessary for some other PLCs, but causes problems with Omron. What is the issue with the string length not being calculated properly? Is it the length of the read string or the calculated length of the string which is to be written to the PLC?

**Comment by kyle-github** [comment]
I think @ptsOSL's PR is going to fix this.  If not, it will at least be a better base to start from.

**Comment by kyle-github** [comment]
Please reopen once @ptsOSL's fix is out and it does not solve the problem.
